name: CI

on:
  pull_request: {}
  merge_group: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nixery.dev/shell/bash/findutils/coreutils/gnutar/gnugrep/gzip/go/golangci-lint/dyff/gnumake/git/nodejs_20
      volumes:
        - /tmp:/__e/node20
    steps:
      - name: Github Actions hacks...
        run: |
          mkdir -p /__e/node20/bin
          ln -sf $(type -p node) /__e/node20/bin/node
          ln -sf $(type -p npm) /__e/node20/bin/npm
          ln -sf $(type -p npx) /__e/node20/bin/npx
          git config --global --add safe.directory '*'

      - uses: actions/checkout@v4

      - run: make lint --keep-going

      - run: make unit-test

      - run: make integration-test

      - run: make benchmark
